Add `Getting Started` section to the matchstick docs
graphprotocol/docs pull request #101
Opened 2022-03-30 17:35 UTC by dimitrovmaksim

In order for all the needed info to be in one place, I have added all the info from the matchstick repo as a new `Getting Started` section in the matchstick docs. Now users don't need to follow links to the repo or demo-subgraph to see how to run docker, what dependencies should be installed, or how to configure custom test and/or libs folders.
Also adds instructions for mocking IPFS files and how to run matchstick in coverage mode.

@graphprotocol/docs-reviewers

2022-04-07 11:54 UTC, GundamDweeb commented
Have reviewed - Looks good!

2022-04-13 08:07 UTC, schmidsi requested changes
Thanks a lot for this submission. This makes a lot of sense. I just added some small corrections, otherwise we are good to go.

2022-04-13 08:07 UTC, schmidsi commented on pages/en/developer/matchstick.mdx
> +# Export ipfs.map() callback in order for matchstck to detect it
This is not a proper comment in TypeScript/AssemblyScript

2022-04-13 08:07 UTC, schmidsi commented on pages/en/developer/matchstick.mdx
> +❗ Since `graph-node` depends on diesel (and diesel requires a local postgres installation) we highly advise using the commands below as adding it in any other way may cause unexpected errors! If you
The dependency on diesel does not really help here and is just confusing in my opinion. It is sufficient to say that graph-node depends on Postgres.

2022-04-13 10:23 UTC, schmidsi approved these changes

2022-04-13 10:23 UTC, merged