Adds moonbeam to hosted service
graphprotocol/docs pull request #143
Opened 2022-06-03 10:37 UTC by albertov19

This PR adds Moonbeam to the hosted service page. Also clarifies that `mbase` is Moonbeam/Moonriver TestNet.

2022-06-03 15:51 UTC, azf20 requested changes
Thanks! Could you also add to this page? https://github.com/graphprotocol/docs/blob/main/pages/en/developer/developer-faq.mdx
(We have this duplication which we should resolve, but that is outside the scope of this PR)

2022-06-07 10:28 UTC, albertov19 commented
@azf20 Feedback done 😃

2022-06-14 08:24 UTC, ahmadmardeni1 approved these changes

2022-06-20 10:28 UTC, azf20 approved these changes

2022-06-20 10:28 UTC, azf20 commented
Thanks

2022-06-20 10:37 UTC, merged