Update broken link
graphprotocol/docs pull request #165
Opened 2022-07-11 11:25 UTC by rafaelugolini

2022-07-11 17:09 UTC, benface approved these changes
🤣

2022-07-12 07:39 UTC, dimitrovmaksim commented
:arrow_upper_left: :facepalm:

2022-07-12 11:27 UTC, rafaelugolini commented
@benface, since there was a conflict, I rebased and also updated the links in the other languages

2022-07-12 11:30 UTC, rafaelugolini commented
> @benface, since there was a conflict, I rebased and also updated the links in the other languages

I just saw that I shouldn't have done so I deleted the previous commit and only left the rebase

2022-07-12 21:11 UTC, benface commented
Thank you @rafaelugolini!

> I just saw that I shouldn't have done so I deleted the previous commit and only left the rebase

Actually, for fixing this sort of stuff, it's perfectly fine to do it in all languages – when Crowdin updates those files eventually, surely the same fix will have been applied there too. But it's better if we don't have to wait for that.

2022-07-13 07:02 UTC, rafaelugolini commented
@benface I added the fix back :)

2022-07-13 16:50 UTC, benface commented on pages/en/developing/unit-testing-framework.mdx
> +This means you have used `console.log` in your code, which is not supported by AssemblyScript. Please consider using the [Logging API](https://thegraph.com/docs/en/developer/assemblyscript-api/#loggi
```suggestion
This means you have used `console.log` in your code, which is not supported by AssemblyScript. Please consider using the [Logging API](/developer/assemblyscript-api/#logging-api)
```

2022-07-13 16:50 UTC, benface requested changes
Ugh, I'm sorry for not noticing when I reviewed the first time, but links within content should ideally be (root-) relative and not absolute. That will also ensure that the links don't direct the user to a different language.

2022-07-14 06:44 UTC, rafaelugolini commented
@benface fixed :)

2022-07-14 14:18 UTC, benface approved these changes
Thank you so much, and sorry for the back and forth!

2022-07-14 14:20 UTC, rafaelugolini commented
> Thank you so much, and sorry for the back and forth!

all good :)

2022-07-14 14:27 UTC, merged