Small feature usage suggestion in quick-start
graphprotocol/docs pull request #211
Opened 2022-09-28 16:38 UTC by t-proctor

Suggest adding a mention of a great feature, `--index-events` in the quick-start article

2022-09-28 17:21 UTC, schmidsi requested changes
I really like this note. That said, I think we should clearly say what it does: It bootstraps the subgraph with entities in the schema and simple mappings for each emitted event.

2022-09-29 10:26 UTC, t-proctor commented
> I really like this note. That said, I think we should clearly say what it does: It bootstraps the subgraph with entities in the schema and simple mappings for each emitted event.

Added this, thanks!

2022-10-18 21:16 UTC, azf20 approved these changes

2022-11-01 16:35 UTC, schmidsi approved these changes

2022-11-01 16:35 UTC, merged