Updating "Migrating an Existing Subgraph to The Graph Network" page
graphprotocol/docs pull request #37
Opened 2022-01-20 20:20 UTC by ahmadmardeni1

- I've fixed some readability issues.
- Added "When not to Migrate?" section.
- Added Curation Station links.

2022-01-21 14:55 UTC, schmidsi requested changes
Thanks for your input. I added a few comments.

2022-01-21 14:55 UTC, schmidsi commented on pages/en/hosted-service/migrating-subgraph.mdx
> +- Is not generating too many queries, and at the same time you are not willing to self-signal.
Good idea with this section. We should be careful about the wording here. Too little queries is not a reason to not migrate. Also self-signalling is not necessary a problem. But these are good reasons to not migrate:
- Usage of IPFS
- Usage of full-text search
- Deployed on other chains than Ethereum mainnet

2022-01-21 14:55 UTC, schmidsi commented on pages/en/hosted-service/migrating-subgraph.mdx
> +Feel free to leverage the Curation Station (Unofficial) [Discord](https://discord.gg/GVfH3PgANH) and [Telegram](https://t.me/+RqzR_Y_a5eY2Zjdh) to let Curators know that your subgraph is ready to be
These are unofficial sources and we should not reference them on the public docs. But a paragraph that explains the general process of advertising a subgraph is definitely good. Main place for such thing is the official The Graph Discord: thegraph.com/discord

2022-01-22 17:53 UTC, ahmadmardeni1 commented
Done. @schmidsi
Also, changed the expired link:

![Capture](https://user-images.githubusercontent.com/63211822/150649886-384c8abc-a658-460d-922b-9043b5a49337.PNG)

2022-01-24 00:15 UTC, azf20 requested changes
Thanks so much for this PR! Some small wording suggestions in line

2022-01-24 00:15 UTC, azf20 commented on pages/en/hosted-service/migrating-subgraph.mdx
> +- Deployed on other chains than Ethereum mainnet.
"Indexing chains other than Ethereum mainnet" might be slightly clearer here, just to be consistent across the documentation (subgraphs are deployed to an instance of Graph Node).

2022-01-24 00:15 UTC, azf20 commented on pages/en/hosted-service/migrating-subgraph.mdx
> +Feel free to leverage the [#Curators channel](https://discord.gg/rC8rBuRtbH) on Discord to let Curators know that your subgraph is ready to be signaled. It would also be helpful if you share your exp
Nice! Maybe works best to clarify how this information helps (maybe "Help curators by giving them some context about your subgraph, and its expected query volume")

2022-01-24 17:40 UTC, ahmadmardeni1 commented
Done. @azf20

2022-02-01 09:26 UTC, azf20 approved these changes

2022-02-01 12:59 UTC, schmidsi approved these changes

2022-02-03 17:40 UTC, merged