feat: derived loader docs
graphprotocol/docs pull request #404
Opened 2023-06-07 18:42 UTC by saihaj

2023-06-07 18:43 UTC, saihaj commented on website/pages/en/developing/assemblyscript-api.mdx
> +As of `graph-node` v0.31.0, `@graphprotocol/graph-ts` v0.31.0 and `@graphprotocol/graph-cli` v0.51.0 the `loadRelated` method is available.
based on this comment it is available https://github.com/graphprotocol/graph-tooling/pull/1190#issuecomment-1533140029 in `graph-node`

2023-06-07 19:39 UTC, azf20 requested changes

2023-06-07 19:39 UTC, azf20 commented on website/pages/en/developing/assemblyscript-api.mdx
> +Given a derived entity type, yuo can load the entity field was derived from. For example, given the following schema:
Might replace with:
This enables loading derived entity fields from within an event handler. For example, given the following schema:

2023-06-15 21:36 UTC, azf20 approved these changes

2023-06-15 21:40 UTC, merged