Add docs for `endBlock`
graphprotocol/docs pull request #494
Opened 2023-08-29 11:04 UTC by incrypto32

2023-08-30 16:05 UTC, azf20 requested changes
Thanks - two small asks!

2023-08-30 16:05 UTC, azf20 commented on website/pages/en/developing/creating-a-subgraph.mdx
> +- `dataSources.source.endBlock`: the optional number of the block that the data source stops indexing at. When provided the dataSource stops indexing at the specified block.
is the block inclusive or exclusive? (i.e. in the example case does it index block 7175245 and stop, or does it stop before indexing 7175245?)

2023-08-30 16:05 UTC, azf20 commented on website/pages/en/developing/creating-a-subgraph.mdx
> +- `dataSources.source.endBlock`: the optional number of the block that the data source stops indexing at. When provided the dataSource stops indexing at the specified block.
Additionally I think worth specifying the `specVersion` from which this is available

2023-09-15 16:17 UTC, azf20 commented
Checking on this one @incrypto32?

2023-12-01 09:06 UTC, tamebadger commented
what is the eta on this being merged ? is it safe to use endBlock now ?

2023-12-04 11:04 UTC, azf20 approved these changes
LGTM thanks!

2023-12-04 11:06 UTC, merged