[ix]: minor chore updates
graphprotocol/docs pull request #645
Opened 2024-04-22 11:54 UTC by yash251

2024-04-22 12:36 UTC, benface commented on website/pages/en/about.mdx
> +Before you start writing your own subgraph, you might want to have a look at the [Graph Explorer](https://thegraph.com/explorer) and explore some of the subgraphs that have already been deployed. The
```suggestion
Before you start writing your own subgraph, you might want to have a look at [Graph Explorer](https://thegraph.com/explorer) and explore some of the subgraphs that have already been deployed. The page for each subgraph contains a playground that lets you query that subgraph's data with GraphQL.
```

Source: https://www.notion.so/edgeandnode/The-Graph-Style-Guide-70a1409024d84bfbb4eccdf0e49b7aa7?pvs=4#4baa7d6f012a43bbadfc1d7180d9c47e (thanks @bermchain!)

2024-04-22 12:38 UTC, benface commented on website/pages/en/network/indexing.mdx
>  - Navigate to the ./terraform directory, this is where all commands should be executed.
```suggestion
- Navigate to the `./terraform` directory, this is where all commands should be executed.
```

I know you didn't change this, but I saw it right below a line you changed so why not.

2024-04-22 12:39 UTC, benface commented on website/pages/en/sunrise.mdx
> +Once your subgraph is published, the [Upgrade Indexer](#what-is-the-upgrade-indexer) will begin serving queries on it, so you can begin making queries immediately, once you have generated an API key
No, "upgrade" [shouldn't be capitalized](https://www.notion.so/edgeandnode/The-Graph-Style-Guide-70a1409024d84bfbb4eccdf0e49b7aa7?pvs=4#09d4ed7a5a5d423aa1074e7ff58e53c1):
```suggestion
Once your subgraph is published, the [upgrade Indexer](#what-is-the-upgrade-indexer) will begin serving queries on it, so you can begin making queries immediately, once you have generated an API key ([learn more](/cookbook/upgrading-a-subgraph/#what-next)).
```

2024-04-22 12:40 UTC, benface requested changes
Looks like the lint is failing, can you please run `pnpm check:fix`? 🙏

2024-04-22 19:44 UTC, benface approved these changes

2024-04-23 10:51 UTC, azf20 approved these changes

2024-04-23 10:52 UTC, merged