docs: added docs hasCode() on ethereum API section
graphprotocol/docs pull request #651
Opened 2024-04-25 11:18 UTC by Shiyasmohd

Documentation for [hasCode()](https://github.com/graphprotocol/graph-node/commit/820d2206f27c91a9ff33325149bb768cb6dc0444) feature on mappings to check whether an address is contract address or an eoa

2024-04-25 12:41 UTC, azf20 requested changes
Looks great! Small request

2024-04-25 12:41 UTC, azf20 commented on website/pages/en/developing/graph-ts/api.mdx
> +The balance of an address can be retrieved using the `ethereum` module. This feature is available from `apiVersion: 0.0.9` defined `subgraph.yaml`. The `getBalance()` retrieves the balance of the spe
I think one nuance to note is that this gives the balance as of the end of the block, rather than at the moment the event is executed

2024-04-25 12:41 UTC, azf20 commented on website/pages/en/developing/graph-ts/api.mdx
> +To check whether an address is a smart contract address or wallet address(EOA), use the `hasCode()` function from the `ethereum` module which will return `boolean`. This feature is available from `ap
Same note that this is as of the end of the block

2024-04-25 12:41 UTC, azf20 commented on website/pages/en/developing/graph-ts/api.mdx
> +The balance of an address can be retrieved using the `ethereum` module. This feature is available from `apiVersion: 0.0.9` defined `subgraph.yaml`. The `getBalance()` retrieves the balance of the spe
Also small update on wording:

 This feature is available from `apiVersion: 0.0.9`, which is defined in the `subgraph.yaml` manifest file.

2024-04-25 13:57 UTC, schmidsi reviewed
Looks good to me otherwise. Great work!

2024-04-26 10:20 UTC, azf20 approved these changes
Nice! Very small amendment suggestions

2024-04-26 10:20 UTC, azf20 commented on website/pages/en/developing/graph-ts/api.mdx
> +The balance of an address can be retrieved using the `ethereum` module. This feature is available from `apiVersion: 0.0.9` which is defined `subgraph.yaml`. The `getBalance()` retrieves the balance o
```suggestion
The native token balance of an address can be retrieved using the `ethereum` module. This feature is available from `apiVersion: 0.0.9` which is defined `subgraph.yaml`. The `getBalance()` retrieves the balance of the specified address as of the end of the block in which the event is triggered.
```

2024-04-26 10:20 UTC, azf20 commented on website/pages/en/developing/graph-ts/api.mdx
> +To check whether an address is a smart contract address or an externally owned address(EOA), use the `hasCode()` function from the `ethereum` module which will return `boolean`. This feature is avail
```suggestion
To check whether an address is a smart contract address or an externally owned address (EOA), use the `hasCode()` function from the `ethereum` module which will return `boolean`. This feature is available from `apiVersion: 0.0.9` which is defined `subgraph.yaml`.
```

2024-04-26 14:02 UTC, merged