add Timestamp scalar
graphprotocol/docs pull request #683
Opened 2024-05-24 05:58 UTC by yash251

solves #676

2024-05-24 15:21 UTC, benface approved these changes

2024-05-24 21:53 UTC, azf20 requested changes

2024-05-27 21:50 UTC, azf20 approved these changes

2024-05-27 21:50 UTC, azf20 commented
@benface is this `pnpm lock` change ok?

2024-05-29 17:14 UTC, benface commented
@azf20 – Thanks for the tag. I just merged `main` into this branch and resolved conflicts using `main`, so this PR no longer has changes to `pnpm-lock.yaml`. I will merge it now.

2024-05-29 17:53 UTC, merged