Scrub HS from docs
graphprotocol/docs pull request #740
Opened 2024-08-13 18:14 UTC by MichaelMacaulay

2024-08-13 22:03 UTC, idalithb requested changes

2024-08-13 22:03 UTC, idalithb commented on website/pages/en/developing/creating-a-subgraph.mdx
-it might be a good idea to remove the code that follows this description (it's the same code found in the "deploying a subgraph to hosted service" deleted page)

2024-08-14 15:03 UTC, MichaelMacaulay commented on website/pages/en/developing/creating-a-subgraph.mdx
Good call, thank you!

2024-08-14 16:16 UTC, idalithb approved these changes

2024-08-14 16:19 UTC, merged