adding faq/bug fix to bottom of delegation docs
graphprotocol/docs pull request #84
Opened 2022-03-09 22:56 UTC by brandonleekramer

Brandon (UX/Design) found this bug a couple weeks ago while attempting to delegate and while scanning Discord for other data. Brandon shared this with the Product Engineering team (Nas) in Asana and the Graphtronauts on Telegram before Adam Fuller suggested that this FAQ/Bug would be best shared on the docs page.

2022-03-10 16:26 UTC, azf20 requested changes
Hey thanks! Suggested some edits to the explanation.

2022-03-10 16:26 UTC, azf20 commented on pages/en/delegating.mdx
> +At times, attempts to delegate to indexers via MetaMask can fail and result in prolonged periods of "Pending" or "Queued" transaction attempts. For example, a user may attempt to delegate and run out
Some edits for accuracy:

> delegate and run out of ETH to cover the gas costs to complete the transaction

...delegate with an insufficient gas fee, given current prices...

>  which pushes the initial transaction into a queue and raises the most recent attempt(s) to "Pending" in place of the initial attempt

... but these will not be processed until the initial transaction is mined, as transactions for an address must be processed in order.

> the transactions attempts will accrue gas fees without any guarantee that subsequent attempts will be successful

... the cancellation transactions will incur gas fees.

> The cheapest known fix to this bug

A simpler resolution

2022-03-14 19:44 UTC, brandonleekramer commented
Thank you, Adam. I've implemented these suggestions into the docs and pushed again.

2022-04-20 09:09 UTC, azf20 requested changes

2022-04-20 09:09 UTC, azf20 commented on pages/en/delegating.mdx
> +At times, attempts to delegate to indexers via MetaMask can fail and result in prolonged periods of "Pending" or "Queued" transaction attempts. For example, a user may attempt to delegate with an ins
sorry last one on this - seems to be a typo
```
encoA simpler resolutionuntered
```

2022-04-20 21:51 UTC, azf20 approved these changes

2022-04-20 21:51 UTC, azf20 commented
LGTM, thanks!

2022-04-20 21:51 UTC, merged