Updating all pages
graphprotocol/docs pull request #98
Opened 2022-03-24 18:46 UTC by ahmadmardeni1

I've made more than 100 edits, some of them are:
- Grammatical errors.
- Typos.
- Extra/missed commas/dots.

I've spent a lot of time on this and updated all pages, so please let me know if there are any other additional edits required.

2022-03-24 18:47 UTC, ahmadmardeni1 commented
cc @schmidsi

2022-04-19 21:03 UTC, azf20 requested changes
Thanks for the detailed fixes across a lot of files, some eagle-eyed spots there! Some small tweaks (mostly we say dapp not dApp). There might be some conflicts at merge time as this is pretty wide ranging

2022-04-19 21:03 UTC, azf20 commented on pages/en/hosted-service/migrating-subgraph.mdx
> +Remember that it's a dynamic and growing market, but how you interact with it is in your control. There is no maximum or minimum price specified in the protocol or the Gateways. For example, you can
dapp not dApp

2022-04-19 21:03 UTC, azf20 commented on pages/en/hosted-service/what-is-hosted-service.mdx
> +If you don't have an account on the Hosted Service, you can signup with your Github account. Once you authenticate, you can start creating subgraphs through the UI and deploying them from your termin
I think this sentence understates the number of supported networks at this point, but that is perhaps outside the scope of this PR

2022-04-19 21:03 UTC, azf20 commented on pages/en/studio/subgraph-studio.mdx
> +Querying subgraphs generates query fees, used to reward [indexers](/indexing) on the Graph network. If you’re a dApp developer or subgraph developer, the Studio will empower you to build better subgr
dapp not dApp

2022-04-19 21:03 UTC, azf20 commented on pages/en/studio/subgraph-studio.mdx
> +Regardless of whether you’re a dApp developer or a subgraph developer, you’ll need to manage your API keys. This is important for you to be able to query subgraphs because API keys make sure the conn
dapp not dApp

2022-04-20 21:34 UTC, ahmadmardeni1 commented
Hey Adam, thank you! @azf20

2022-04-20 21:48 UTC, azf20 requested changes
nice thanks so much! I think there are some conflicts to resolve, could you take a look?

2022-04-20 21:48 UTC, azf20 commented on pages/en/studio/subgraph-studio.mdx
> +Querying subgraphs generates query fees, used to reward [indexers](/indexing) on the Graph network. If you’re a dpp developer or subgraph developer, the Studio will empower you to build better subgra
small spelling!

2022-04-24 00:22 UTC, ahmadmardeni1 commented
Oh sorry, didn't notice the comment. 
Conflicts are resolved. @azf20

2022-04-25 14:57 UTC, azf20 commented
Thanks @ahmadmardeni1! I still see two conflicts? Sorry if they were more recently introduced

2022-04-25 17:27 UTC, ahmadmardeni1 commented
Yes, they were recently introduced. No problem, just resolved them! @azf20

2022-04-28 20:20 UTC, azf20 approved these changes

2022-04-28 20:21 UTC, merged